/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "app": [],
    "search.user": [],
    "manage.index": [],
    "manage.unit.index": [],
    "manage.unit.create": [],
    "manage.unit.store": [],
    "manage.unit.show": [
        {
            "name": "unit",
            "required": true
        }
    ],
    "manage.unit.edit": [
        {
            "name": "unit",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.unit.update": [
        {
            "name": "unit",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.unit.destroy": [
        {
            "name": "unit",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.unit.division.index": [
        {
            "name": "unit",
            "required": true
        }
    ],
    "manage.unit.division.create": [
        {
            "name": "unit",
            "required": true
        }
    ],
    "manage.unit.division.store": [
        {
            "name": "unit",
            "required": true
        }
    ],
    "manage.unit.division.show": [
        {
            "name": "unit",
            "required": true
        },
        {
            "name": "division",
            "required": true
        }
    ],
    "manage.unit.division.edit": [
        {
            "name": "unit",
            "required": true
        },
        {
            "name": "division",
            "required": true
        }
    ],
    "manage.unit.division.update": [
        {
            "name": "unit",
            "required": true
        },
        {
            "name": "division",
            "required": true
        }
    ],
    "manage.unit.division.destroy": [
        {
            "name": "unit",
            "required": true
        },
        {
            "name": "division",
            "required": true
        }
    ],
    "manage.permission.index": [],
    "manage.permission.create": [],
    "manage.permission.store": [],
    "manage.permission.show": [
        {
            "name": "permission",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.permission.edit": [
        {
            "name": "permission",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.permission.update": [
        {
            "name": "permission",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.permission.destroy": [
        {
            "name": "permission",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.role.index": [],
    "manage.role.create": [],
    "manage.role.store": [],
    "manage.role.show": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.role.edit": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.role.update": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.role.destroy": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.user.index": [],
    "manage.user.create": [],
    "manage.user.store": [],
    "manage.user.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.user.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.user.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "manage.user.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "project.index": [],
    "project.store": [],
    "project.show": [
        {
            "name": "project",
            "required": true
        }
    ],
    "project.version.sync": [
        {
            "name": "project",
            "required": true
        }
    ],
    "project.version.index": [
        {
            "name": "project",
            "required": true
        }
    ],
    "project.version.create": [
        {
            "name": "project",
            "required": true
        }
    ],
    "project.version.store": [
        {
            "name": "project",
            "required": true,
            "binding": "code"
        }
    ],
    "project.version.show": [
        {
            "name": "project",
            "required": true
        },
        {
            "name": "version",
            "required": true
        }
    ],
    "project.version.edit": [
        {
            "name": "project",
            "required": true
        },
        {
            "name": "version",
            "required": true
        }
    ],
    "project.version.update": [
        {
            "name": "project",
            "required": true
        },
        {
            "name": "version",
            "required": true
        }
    ],
    "project.version.destroy": [
        {
            "name": "project",
            "required": true
        },
        {
            "name": "version",
            "required": true
        }
    ],
    "api.auth.check.user": [],
    "register.create": [],
    "register.store": [],
    "register.created": [],
    "login.create": [],
    "login.store": [],
    "logout.destroy": []
}
}
export {};
